# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keylightd < Formula
  desc "Daemon and CLI tool for managing Elgato Key Lights on your local network"
  homepage "https://github.com/jmylchreest/keylightd"
  version "0.0.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.17/keylightd_0.0.17_darwin_amd64.tar.gz"
      sha256 "07473fc013a2f631acfb663f48e91d5162734c468d44ff213c3f0560ae520b29"

      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.17/keylightd_0.0.17_darwin_arm64.tar.gz"
      sha256 "ca5369991856b0fa81b8b3ccf77ec725d8189aa5df76b544e5a2f8d8a9d433c7"

      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.17/keylightd_0.0.17_linux_amd64.tar.gz"
      sha256 "0a65e72738147d412b636585df407bbccbc2db43f0b5d131d4fcfd85d2723c5d"
      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.17/keylightd_0.0.17_linux_arm64.tar.gz"
      sha256 "d5eb7ce10fa1bd2aa92e09770541d24139246d60f4d7ca79c7ee7728f81f227d"
      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
  end

  def caveats
    <<~EOS
      keylightd daemon has been installed!

      To start keylightd manually:
        keylightd

      To start automatically with Homebrew services:
        brew services start keylightd

      To stop the service:
        brew services stop keylightd

      To restart the service:
        brew services restart keylightd

      To check service status:
        brew services list | grep keylightd

      Once started, control your lights with:
        keylightctl light list
        keylightctl --help

      Configuration will be created at: ~/.config/keylight/
      Service logs will be written to: $(brew --prefix)/var/log/keylightd.log
    EOS
  end

  service do
    run bin/"keylightd"
    keep_alive true
    restart_delay 5
    process_type :background
    run_type :immediate
  end

  test do
    system "#{bin}/keylightd", "-h"
    system "#{bin}/keylightctl", "version"
  end
end
