# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keylightd < Formula
  desc "Daemon and CLI tool for managing HTTP-based Key Lights, including Elgato models"
  homepage "https://github.com/jmylchreest/keylightd"
  version "0.0.24"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.24/keylightd_0.0.24_darwin_amd64.tar.gz"
      sha256 "b6526e10736071c4c3205345b71394ce3559af5d40ace367dcb8bef10e132f8c"

      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.24/keylightd_0.0.24_darwin_arm64.tar.gz"
      sha256 "e0c488b6c8e01843ee825e588adabd51137ac01b31b7c3f45ad2c3625df13db7"

      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.24/keylightd_0.0.24_linux_amd64.tar.gz"
      sha256 "235f3decf59649e96981d1b6df7042c5ede956f0c2dcb7b2bcd7c66fc688e4d6"
      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.24/keylightd_0.0.24_linux_arm64.tar.gz"
      sha256 "556a38b17bbdac4f2aaa57e3ee1b81051b05db5ca311210b713ae2798642b9b6"
      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
  end

  def caveats
    <<~EOS
      keylightd daemon has been installed!

      To start keylightd manually:
        keylightd

      To start automatically with Homebrew services:
        brew services start keylightd

      To stop the service:
        brew services stop keylightd

      To restart the service:
        brew services restart keylightd

      To check service status:
        brew services list | grep keylightd

      Once started, control your lights with:
        keylightctl light list
        keylightctl --help

      Configuration will be created at: ~/.config/keylightd/
      Service logs will be written to: $(brew --prefix)/var/log/keylightd.log
    EOS
  end

  service do
    run bin/"keylightd"
    keep_alive true
    restart_delay 5
    process_type :background
    run_type :immediate
  end

  test do
    system "#{bin}/keylightd", "-h"
    system "#{bin}/keylightctl", "version"
  end
end
