# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keylightd < Formula
  desc "Daemon and CLI tool for managing HTTP-based Key Lights, including Elgato models"
  homepage "https://github.com/jmylchreest/keylightd"
  version "0.0.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.22/keylightd_0.0.22_darwin_amd64.tar.gz"
      sha256 "6b0ca836a2ba10f3f350e15397976778b2f649c9782cb010596b7ac890969dc2"

      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.22/keylightd_0.0.22_darwin_arm64.tar.gz"
      sha256 "c599de68fb44a0145c99ea4de48542a05e04161dc8bc286b9cf28bb56a43d21e"

      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.22/keylightd_0.0.22_linux_amd64.tar.gz"
      sha256 "483c126344217fd3a85a4c63258f240b9a2894ed1f897aa89028735a0df71341"
      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmylchreest/keylightd/releases/download/v0.0.22/keylightd_0.0.22_linux_arm64.tar.gz"
      sha256 "506a657f8e13a8aa3f3f0249c48d044491e603aefcc304cf5ecd1e18a9f5129d"
      def install
        bin.install "keylightd"
        bin.install "keylightctl"
      end
    end
  end

  def caveats
    <<~EOS
      keylightd daemon has been installed!

      To start keylightd manually:
        keylightd

      To start automatically with Homebrew services:
        brew services start keylightd

      To stop the service:
        brew services stop keylightd

      To restart the service:
        brew services restart keylightd

      To check service status:
        brew services list | grep keylightd

      Once started, control your lights with:
        keylightctl light list
        keylightctl --help

      Configuration will be created at: ~/.config/keylightd/
      Service logs will be written to: $(brew --prefix)/var/log/keylightd.log
    EOS
  end

  service do
    run bin/"keylightd"
    keep_alive true
    restart_delay 5
    process_type :background
    run_type :immediate
  end

  test do
    system "#{bin}/keylightd", "-h"
    system "#{bin}/keylightctl", "version"
  end
end
